name: torneo_baloncesto
description: A new Flutter project for managing basketball tournaments.

publish_to: 'none'

version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  uuid: ^3.0.4
  provider: ^6.0.2
  google_maps_flutter: ^2.1.1
  local_auth: ^2.1.3
  supabase: ^0.3.6
  supabase_flutter: ^0.3.3
  email_validator: ^2.0.0
  flutter_staggered_grid_view: ^0.4.0
  flutter_animate: ^2.0.1
  path_provider: ^2.0.11
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  intl: ^0.17.0
  image_picker: ^1.0.2
  multi_select_flutter: ^4.1.1
  #google_maps_flutter: ^2.0.6
  geolocator: ^7.7.1
  http: ^0.13.3
  file_picker: ^4.0.0
  url_launcher: ^6.0.9
  material_design_icons_flutter: ^5.0.6595
  permission_handler: ^10.2.0
  responsive_builder: ^0.4.3
  geolocator_web: ^2.0.6
  google_maps_flutter_web: ^0.3.0
  location: ^4.3.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

assets:
  - assets/images/background.jpg
  - assets/images/logo.png
  - assets/fonts/


//version: 1.0.0+1

//environment:
//  sdk: ">=2.12.0 <3.0.0"


