name: torneo_baloncesto
description: A new Flutter project for managing basketball tournaments.

publish_to: 'none'

version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.2
  google_maps_flutter: ^2.1.1
  local_auth: ^2.1.3
  supabase: ^0.2.9
  email_validator: ^2.0.0
  flutter_staggered_grid_view: ^0.4.0
  flutter_animate: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

assets:

  - assets/images/logo.jpg
  - assets/images/fondo1.jpg
  - assets/fonts/


//version: 1.0.0+1

//environment:
//  sdk: ">=2.12.0 <3.0.0"


